# Generated by Django 5.0.6 on 2026-05-01 14:34

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('file_name', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTING', 'Extracting'), ('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('template_guess', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_in_document', models.IntegerField()),
                ('invoice_number', models.CharField(blank=True, default='', max_length=128)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=512)),
                ('customer_code', models.CharField(blank=True, default='', max_length=128)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('customer_tel', models.CharField(blank=True, default='', max_length=64)),
                ('sales_rep', models.CharField(blank=True, default='', max_length=200)),
                ('route', models.CharField(blank=True, default='', max_length=128)),
                ('territory', models.CharField(blank=True, default='', max_length=200)),
                ('payment_type', models.CharField(blank=True, default='', max_length=64)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('header_discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('return_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='LKR', max_length=8)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('EDITED', 'Edited'), ('COMMITTED', 'Committed')], default='DRAFT', max_length=20)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'index_in_document'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('unit_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('invoice_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.invoicedraft')),
            ],
            options={
                'ordering': ['invoice_draft', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', '-created_at'], name='documents_d_organiz_6d035c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'status'], name='documents_d_organiz_b8cccc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicedraft',
            unique_together={('document', 'index_in_document')},
        ),
    ]
